apiVersion: kops.k8s.io/v1alpha2
kind: Cluster
metadata:
  creationTimestamp: null
  name: kops-demo.lab-aws.monetplus.cz
spec:
  api:
    loadBalancer:
      type: Public
  authorization:
    rbac: {}
  channel: stable
  cloudProvider: aws
  configBase: s3://monetplus-lab-kops-demo/kops-demo.lab-aws.monetplus.cz
  etcdClusters:
  - cpuRequest: 200m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: main
  - cpuRequest: 100m
    etcdMembers:
    - instanceGroup: master-eu-central-1a
      name: a
    memoryRequest: 100Mi
    name: events
  iam:
    allowContainerRegistry: true    
    legacy: false
  kubelet:
    anonymousAuth: false
    authenticationTokenWebhook: true
    authorizationMode: Webhook
  # https://kops.sigs.k8s.io/operations/service_account_token_volumes/
  kubeAPIServer:
    apiAudiences:
      - api
      - istio-ca
    serviceAccountIssuer: kubernetes.default.svc
    serviceAccountKeyFile:
      - /srv/kubernetes/server.key
    serviceAccountSigningKeyFile: /srv/kubernetes/server.key
  kubernetesApiAccess:
  - 0.0.0.0/0
  kubernetesVersion: 1.17.9
  masterInternalName: api.internal.kops-demo.lab-aws.monetplus.cz
  masterPublicName: api.kops-demo.lab-aws.monetplus.cz
  networkCIDR: 172.20.0.0/16
  networking:
    kubenet: {}
  nonMasqueradeCIDR: 100.64.0.0/10
  sshAccess:
  - 0.0.0.0/0
  subnets:
  - cidr: 172.20.32.0/19
    name: eu-central-1a
    type: Public
    zone: eu-central-1a
  - cidr: 172.20.64.0/19
    name: eu-central-1b
    type: Public
    zone: eu-central-1b
  - cidr: 172.20.96.0/19
    name: eu-central-1c
    type: Public
    zone: eu-central-1c
  topology:
    dns:
      type: Public
    masters: public
    nodes: public
  # https://kops.sigs.k8s.io/iam_roles/
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": "route53:ChangeResourceRecordSets",
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": "route53:ListHostedZones",
          "Resource": "*"
        },
        {
          "Effect": "Allow",
          "Action": "route53:ListResourceRecordSets",
          "Resource": "*"
        }
      ]

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops-demo.lab-aws.monetplus.cz
  name: master-eu-central-1a
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3a.small
  maxSize: 1
  minSize: 1
  maxPrice: "0.05"
  nodeLabels:
    kops.k8s.io/instancegroup: master-eu-central-1a
  role: Master
  rootVolumeSize: 20
  subnets:
    - eu-central-1a

---

apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: null
  labels:
    kops.k8s.io/cluster: kops-demo.lab-aws.monetplus.cz
  name: nodes
spec:
  image: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17
  machineType: t3a.medium
  maxSize: 1
  minSize: 1
  maxPrice: "0.05"
  nodeLabels:
    kops.k8s.io/instancegroup: nodes
  role: Node
  rootVolumeSize: 50
  subnets:
    - eu-central-1a
    - eu-central-1b
    - eu-central-1c