apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio-operator
spec:
  # https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/#IstioOperatorSpec
  profile: default
  addonComponents:
    kiali:
      enabled: true
    grafana:
      enabled: true
    prometheus:
      enabled: true
    tracing:
      enabled: true
  meshConfig:
    enableTracing: true
    enablePrometheusMerge: true
    # uncomment to enable access logging
    # accessLogFile: "/dev/stdout"
    # access logging disabled
    accessLogFile: ""
    accessLogEncoding: JSON
    accessLogFormat: ""
    # https://istio.io/latest/docs/tasks/observability/distributed-tracing/configurability/
    defaultConfig:
      tracing:
        # range of 0.0 to 100.0 with a precision of 0.01. For example, to trace 5 requests out of every 10000, use 0.05 as the value here.
        # FIXME change to a lower value for production cluster
        sampling: 100.0
  #        zipkin:
  #          address: "standalone-jaeger-with-zipkin-endpoint:port"
  values:
    gateways:
      istio-ingressgateway:
        sds:
          enabled: true
        serviceAnnotations:
          # https://kubernetes.io/docs/concepts/services-networking/service/#aws-nlb-support
          service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
          service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
          service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "product=kops-demo,domain=istio.lab-aws.monetplus.cz"
          # https://github.com/istio/istio/issues/16778#issuecomment-528244042
          service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-central-1:850420079329:certificate/f8aa08e9-621c-49ce-b121-8c038e43f9ea"
          service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
          service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
          external-dns.alpha.kubernetes.io/ttl: "60"
          external-dns.alpha.kubernetes.io/hostname: "istio.lab-aws.monetplus.cz"
    global:
      logging:
        level: "default:info"
      logAsJson: true
      proxy:
        logLevel: warning
        componentLogLevel: "misc:error"
