# Required

#awsRegion: eu-central-1

#clusterName: kops-demo.k8s.local

#stateStore: s3://monetplus-lab-kops-demo

# Defaults

#kubernetesVersion: 1.16.10
kubernetesNodeImage: kope.io/k8s-1.16-debian-stretch-amd64-hvm-ebs-2020-01-17

masterVolumeSize: 20 # GB
masterCount: 1
masterInstance: t3a.small
masterMaxPrice: 0.05 # $

# https://aws.amazon.com/ec2/spot/instance-advisor/

nodeVolumeSize: 50 # GB
nodeCount: 1
nodeInstance: t3a.medium
nodeMaxPrice: 0.05 # $